In [ ]:
import pandas as pd
import re
from sklearn.preprocessing import LabelEncoder


In [ ]:
df = pd.read_excel('//content/drive/MyDrive/dataset-finalLabels.xlsx')


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df.head()

Serial no:                                           Comments  \
0           1  ദൈവത്തെ ഓർത്തു ഇനി സം.. വിധാനം ചെയ്യരുത് 🙏🙏🙏മോ...   
1           2  തിയേറ്ററിൽ ആളുകൾ ഉറങ്ങിയാണല്ലോ ആറാട്ട് നെ സ്വീ...   
2           3  അപ്പോ തുടങ്ങിയല്ലേ നെയ്യാറ്റിൻകര ഗോപന്റെ ആറാട്...   
3           4  ആർക്കോ വേണ്ടി കോമാളിത്തരം കാണിക്കുന്ന സൂപ്പർ സ...   
4           5              Adipoli movie 5/5. Unexpected climax👏   

  Majority Emotion  
0            Anger  
1          Sarcasm  
2       Excitement  
3   Affection/Love  
4            Happy

In [ ]:
def clean_text(text):
    # Remove English characters
    text = re.sub(r'[a-zA-Z]', '', text)
    # Remove digits
    text = re.sub(r'\d', '', text)
     # Remove symbols like '.', '/', ',' etc.

    text = re.sub(r'[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251]+', '', text)
    return text

In [ ]:
df['Comments']=df['Comments'].apply(clean_text)

In [ ]:
df.head()

Serial no:                                           Comments  \
0           1  ദൈവത്തെ ഓർത്തു ഇനി സം.. വിധാനം ചെയ്യരുത് മോഹൻല...   
1           2  തിയേറ്ററിൽ ആളുകൾ ഉറങ്ങിയാണല്ലോ ആറാട്ട് നെ സ്വീ...   
2           3  അപ്പോ തുടങ്ങിയല്ലേ നെയ്യാറ്റിൻകര ഗോപന്റെ ആറാട്ട്    
3           4  ആർക്കോ വേണ്ടി കോമാളിത്തരം കാണിക്കുന്ന സൂപ്പർ സ...   
4           5                                               /.     

  Majority Emotion  
0            Anger  
1          Sarcasm  
2       Excitement  
3   Affection/Love  
4            Happy

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Serial no:        9994 non-null   int64 
 1   Comments          9994 non-null   object
 2   Majority Emotion  9993 non-null   object
dtypes: int64(1), object(2)
memory usage: 234.4+ KB


In [ ]:
label_encoder = LabelEncoder()
df['Emotion'] = label_encoder.fit_transform(df['Majority Emotion'])

In [ ]:
df

Serial no:                                           Comments  \
0              1  ദൈവത്തെ ഓർത്തു ഇനി സം.. വിധാനം ചെയ്യരുത് മോഹൻല...   
1              2  തിയേറ്ററിൽ ആളുകൾ ഉറങ്ങിയാണല്ലോ ആറാട്ട് നെ സ്വീ...   
2              3  അപ്പോ തുടങ്ങിയല്ലേ നെയ്യാറ്റിൻകര ഗോപന്റെ ആറാട്ട്    
3              4  ആർക്കോ വേണ്ടി കോമാളിത്തരം കാണിക്കുന്ന സൂപ്പർ സ...   
4              5                                               /.     
...          ...                                                ...   
9989        9990                               പൊളി മച്ചാനെ........   
9990        9991              കാണുന്നതിനെ മുൻപേ ഒരു  അത് നിർബന്ധ..    
9991        9992  വീഡിയോ ലൈക്‌ ചെയ്തതിന് ശേഷം വീഡിയോ കണ്ടവർ ഇവിട...   
9992        9993                              മുത്തെ പൊളിച്ചു......   
9993        9994                                              അണ്ണാ   

     Majority Emotion  Emotion  
0               Anger        2  
1             Sarcasm        8  
2          Excitement        3  
3      Affection/Love        1  
4               Happy        5  
...               ...      ...  
9989            Happy        5  
9990            Happy        5  
9991            Happy        5  
9992            Happy        5  
9993            Happy        5  

[9994 rows x 4 columns]

In [ ]:
df.head()

Serial no:                                           Comments  \
0           1  ദൈവത്തെ ഓർത്തു ഇനി സം.. വിധാനം ചെയ്യരുത് മോഹൻല...   
1           2  തിയേറ്ററിൽ ആളുകൾ ഉറങ്ങിയാണല്ലോ ആറാട്ട് നെ സ്വീ...   
2           3  അപ്പോ തുടങ്ങിയല്ലേ നെയ്യാറ്റിൻകര ഗോപന്റെ ആറാട്ട്    
3           4  ആർക്കോ വേണ്ടി കോമാളിത്തരം കാണിക്കുന്ന സൂപ്പർ സ...   
4           5                                               /.     

  Majority Emotion  Emotion  
0            Anger        2  
1          Sarcasm        8  
2       Excitement        3  
3   Affection/Love        1  
4            Happy        5

In [ ]:
df.value_counts('Emotion')

Emotion
5     3218
3     1521
7     1345
8     1336
6     1017
2      659
1      547
9      199
0      111
4       40
10       1
Name: count, dtype: int64

In [ ]:
encoded_labels = df['Emotion'].unique()

# Create a mapping dictionary to map encoded labels to original values
label_mapping = {}
for label in encoded_labels:
    original_value = df[df['Emotion'] == label]['Majority Emotion'].iloc[0]  # Assuming 'original_column' contains original values
    label_mapping[label] = original_value
label_mapping

{2: 'Anger',
 8: 'Sarcasm',
 3: 'Excitement',
 1: 'Affection/Love',
 5: 'Happy',
 7: 'Sad',
 6: 'Humour',
 4: 'Fear',
 0: 'Abusive',
 9: 'Surprise',
 10: nan}

In [ ]:
df = df[df['Emotion'] != 10]


In [ ]:
df

Serial no:                                           Comments  \
0              1  ദൈവത്തെ ഓർത്തു ഇനി സം.. വിധാനം ചെയ്യരുത് മോഹൻല...   
1              2  തിയേറ്ററിൽ ആളുകൾ ഉറങ്ങിയാണല്ലോ ആറാട്ട് നെ സ്വീ...   
2              3  അപ്പോ തുടങ്ങിയല്ലേ നെയ്യാറ്റിൻകര ഗോപന്റെ ആറാട്ട്    
3              4  ആർക്കോ വേണ്ടി കോമാളിത്തരം കാണിക്കുന്ന സൂപ്പർ സ...   
4              5                                               /.     
...          ...                                                ...   
9989        9990                               പൊളി മച്ചാനെ........   
9990        9991              കാണുന്നതിനെ മുൻപേ ഒരു  അത് നിർബന്ധ..    
9991        9992  വീഡിയോ ലൈക്‌ ചെയ്തതിന് ശേഷം വീഡിയോ കണ്ടവർ ഇവിട...   
9992        9993                              മുത്തെ പൊളിച്ചു......   
9993        9994                                              അണ്ണാ   

     Majority Emotion  Emotion  
0               Anger        2  
1             Sarcasm        8  
2          Excitement        3  
3      Affection/Love        1  
4               Happy        5  
...               ...      ...  
9989            Happy        5  
9990            Happy        5  
9991            Happy        5  
9992            Happy        5  
9993            Happy        5  

[9993 rows x 4 columns]

In [ ]:
df.value_counts('Emotion')

Emotion
5    3218
3    1521
7    1345
8    1336
6    1017
2     659
1     547
9     199
0     111
4      40
Name: count, dtype: int64

In [ ]:
df.drop(columns=['Serial no:','Majority Emotion'], inplace=True)




<ipython-input-16-e06e2b146eb6>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['Serial no:','Majority Emotion'], inplace=True)


In [ ]:
df

Comments  Emotion
0     ദൈവത്തെ ഓർത്തു ഇനി സം.. വിധാനം ചെയ്യരുത് മോഹൻല...        2
1     തിയേറ്ററിൽ ആളുകൾ ഉറങ്ങിയാണല്ലോ ആറാട്ട് നെ സ്വീ...        8
2     അപ്പോ തുടങ്ങിയല്ലേ നെയ്യാറ്റിൻകര ഗോപന്റെ ആറാട്ട്         3
3     ആർക്കോ വേണ്ടി കോമാളിത്തരം കാണിക്കുന്ന സൂപ്പർ സ...        1
4                                                  /.          5
...                                                 ...      ...
9989                               പൊളി മച്ചാനെ........        5
9990              കാണുന്നതിനെ മുൻപേ ഒരു  അത് നിർബന്ധ..         5
9991  വീഡിയോ ലൈക്‌ ചെയ്തതിന് ശേഷം വീഡിയോ കണ്ടവർ ഇവിട...        5
9992                              മുത്തെ പൊളിച്ചു......        5
9993                                              അണ്ണാ        5

[9993 rows x 2 columns]

In [ ]:
!pip install nltk


In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
# prompt: implement bag of words vectoriation for above dataset with data in one column and vectors on correspondng rows

from sklearn.feature_extraction.text import CountVectorizer

# Create a CountVectorizer object
vectorizer = CountVectorizer()

# Fit the vectorizer to the data in the "Comments" column
vectorizer.fit(df['Comments'])

# Transform the data into a bag-of-words model
bag_of_words = vectorizer.transform(df['Comments'])

# Convert the bag-of-words model into a DataFrame
bag_of_words_df = pd.DataFrame(bag_of_words.toarray(), columns=vectorizer.get_feature_names_out())

# Concatenate the bag-of-words DataFrame with the original DataFrame
df_with_bow = pd.concat([df, bag_of_words_df], axis=1)

# Print the resulting DataFrame
print(df_with_bow.head())


                                            Comments  Emotion   __  ___  \
0  ദൈവത്തെ ഓർത്തു ഇനി സം.. വിധാനം ചെയ്യരുത് മോഹൻല...      2.0  0.0  0.0   
1  തിയേറ്ററിൽ ആളുകൾ ഉറങ്ങിയാണല്ലോ ആറാട്ട് നെ സ്വീ...      8.0  0.0  0.0   
2  അപ്പോ തുടങ്ങിയല്ലേ നെയ്യാറ്റിൻകര ഗോപന്റെ ആറാട്ട്       3.0  0.0  0.0   
3  ആർക്കോ വേണ്ടി കോമാളിത്തരം കാണിക്കുന്ന സൂപ്പർ സ...      1.0  0.0  0.0   
4                                               /.        5.0  0.0  0.0   

   _____  ________  _ഇന   _ഈ   _എ   _ച  ...  ൾഡൻ   ൾന  ൾപരമ   ൾയ   ൾവ   ൾസ  \
0    0.0       0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0  0.0  0.0  0.0   
1    0.0       0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0  0.0  0.0  0.0   
2    0.0       0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0  0.0  0.0  0.0   
3    0.0       0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0  0.0  0.0  0.0   
4    0.0       0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0  0.0  0.0  0.0   

   ᴄʜᴀʟʟᴇɴɢᴇ  ᴄᴏᴍᴍᴇɴᴛ  ᴜʙᴄʀɪʙᴇ  ᴜʙᴄʀɪʙᴇʀ  
0        0.0      0.0      0.0       

In [ ]:
# prompt: save this vectors into excel sheet

df_with_bow.to_excel('//content/drive/MyDrive/bag_of_words.xlsx')


<ipython-input-23-1191bf86ad4f>:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vectors_df[f"column_{i+1}"] = [vector[i]]
<ipython-input-23-1191bf86ad4f>:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  vectors_df[f"column_{i+1}"] = [vector[i]]
<ipython-input-23-1191bf86ad4f>:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use

Word2Vec Embedding

In [ ]:
#Word Embedding using Word2Vec:

from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize

# Tokenize the comments
tokenized_comments = df['Comments'].apply(word_tokenize)

# Train Word2Vec model
w2v_model = Word2Vec(sentences=tokenized_comments, vector_size=100, window=5, min_count=1, workers=4)



LSTM

In [ ]:
#Preparing Data for LSTM:

from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

# Tokenize comments
tokenizer = Tokenizer()
tokenizer.fit_on_texts(df['Comments'])
sequences = tokenizer.texts_to_sequences(df['Comments'])

# Pad sequences
max_len = max([len(seq) for seq in sequences])
padded_sequences = pad_sequences(sequences, maxlen=max_len)

# Prepare target variable
target = df['Emotion']


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(padded_sequences, target, test_size=0.2, random_state=42)


In [ ]:
#Training LSTM Model:

from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense

# Define model architecture
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index)+1, output_dim=100, input_length=max_len))
model.add(LSTM(100))
model.add(Dense(11, activation='softmax'))

# Compile model
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train model
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))





Epoch 1/10
250/250 [==============================] - 71s 260ms/step - loss: 1.9249 - accuracy: 0.3235 - val_loss: 1.8205 - val_accuracy: 0.3287
Epoch 2/10
250/250 [==============================] - 48s 192ms/step - loss: 1.5696 - accuracy: 0.4503 - val_loss: 1.7591 - val_accuracy: 0.3652
Epoch 3/10
250/250 [==============================] - 49s 194ms/step - loss: 0.9617 - accuracy: 0.6970 - val_loss: 2.0333 - val_accuracy: 0.3612
Epoch 4/10
250/250 [==============================] - 58s 231ms/step - loss: 0.5291 - accuracy: 0.8393 - val_loss: 2.3053 - val_accuracy: 0.3527
Epoch 5/10
250/250 [==============================] - 48s 191ms/step - loss: 0.3343 - accuracy: 0.8970 - val_loss: 2.6533 - val_accuracy: 0.3337
Epoch 6/10
250/250 [==============================] - 51s 204ms/step - loss: 0.2569 - accuracy: 0.9204 - val_loss: 2.9306 - val_accuracy: 0.3392
Epoch 7/10
250/250 [==============================] - 51s 204ms/step - loss: 0.2069 - accuracy: 0.9331 - val_loss: 3.0873 - val_ac

In [ ]:


loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy:", accuracy)


Accuracy: 0.3251625895500183


NAIVE BAYES

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report



In [ ]:
# Split dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(df['Comments'], df['Emotion'], test_size=0.2, random_state=42)




In [ ]:
# Vectorize comments using TF-IDF
vectorizer = TfidfVectorizer()
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)



In [ ]:
# Train Naive Bayes classifier
naive_bayes_model = MultinomialNB()
naive_bayes_model.fit(X_train_vectorized, y_train)



MultinomialNB()

In [ ]:
# Predict on test set
y_pred = naive_bayes_model.predict(X_test_vectorized)



In [ ]:
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Classification report
print(classification_report(y_test, y_pred))

Accuracy: 0.34967483741870936
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        20
           1       0.00      0.00      0.00       129
           2       0.60      0.05      0.08       132
           3       0.41      0.07      0.13       309
           4       0.00      0.00      0.00         3
           5       0.34      0.96      0.50       632
           6       0.36      0.02      0.04       199
           7       0.50      0.19      0.27       271
           8       0.29      0.04      0.07       276
           9       0.00      0.00      0.00        28

    accuracy                           0.35      1999
   macro avg       0.25      0.13      0.11      1999
weighted avg       0.35      0.35      0.23      1999



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Support Vector Machine

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Function to create document vectors using Word2Vec embeddings
def document_vector(word2vec_model, tokenized_document):
    # Initialize an empty array for the document vector
    doc_vector = np.zeros(word2vec_model.vector_size)
    # Initialize a counter to keep track of the number of words in the document
    num_words = 0
    # Loop through each word in the tokenized document
    for word in tokenized_document:
        # If the word is in the vocabulary of the Word2Vec model
        if word in word2vec_model.wv.key_to_index:
            # Add the word vector to the document vector
            doc_vector += word2vec_model.wv[word]
            # Increment the counter
            num_words += 1
    # If at least one word in the document is in the vocabulary
    if num_words > 0:
        # Normalize the document vector by dividing by the number of words
        doc_vector /= num_words
    return doc_vector

# Create document vectors for each tokenized comment
X = np.array([document_vector(w2v_model, comment) for comment in tokenized_comments])

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, df['Emotion'], test_size=0.2, random_state=42)

# Initialize SVM classifier
svm_classifier = SVC()

# Train the classifier
svm_classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = svm_classifier.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.31615807903951976


In [ ]:
# Import the necessary module
from sklearn.metrics import classification_report

# Print the classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        20
           1       0.00      0.00      0.00       129
           2       0.00      0.00      0.00       132
           3       0.00      0.00      0.00       309
           4       0.00      0.00      0.00         3
           5       0.32      1.00      0.48       632
           6       0.00      0.00      0.00       199
           7       0.00      0.00      0.00       271
           8       0.00      0.00      0.00       276
           9       0.00      0.00      0.00        28

    accuracy                           0.32      1999
   macro avg       0.03      0.10      0.05      1999
weighted avg       0.10      0.32      0.15      1999



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


TF IDF Vectorization


In [ ]:
# word embedding using TF IDF vectorizer

from sklearn.feature_extraction.text import TfidfVectorizer

# Create a TfidfVectorizer object
vectorizer = TfidfVectorizer()

# Fit the vectorizer on the comments
X = vectorizer.fit_transform(df['Comments'])

# Transform the comments into TF-IDF vectors
X = vectorizer.transform(df['Comments'])

# Print the shape of the TF-IDF matrix
print(X.shape)


(9993, 2581)


Support Vector Machine using TFIDF vectors

In [ ]:


# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, df['Emotion'], test_size=0.2, random_state=42)

# Initialize the SVM classifier
svm_classifier = SVC()

# Train the classifier
svm_classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = svm_classifier.predict(X_test)

# Calculate the accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print the classification report
print(classification_report(y_test, y_pred))


Accuracy: 0.37318659329664833
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        20
           1       0.57      0.03      0.06       129
           2       0.43      0.15      0.22       132
           3       0.36      0.15      0.21       309
           4       0.00      0.00      0.00         3
           5       0.36      0.85      0.51       632
           6       0.38      0.09      0.15       199
           7       0.50      0.34      0.40       271
           8       0.28      0.12      0.16       276
           9       0.00      0.00      0.00        28

    accuracy                           0.37      1999
   macro avg       0.29      0.17      0.17      1999
weighted avg       0.38      0.37      0.30      1999



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Naive Bayes using TFIDF Vectors

In [ ]:

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix, accuracy_score

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, df['Emotion'], test_size=0.2, random_state=42)

# Train the Naive Bayes model
clf = MultinomialNB()
clf.fit(X_train, y_train)

# Make predictions on the test set
y_pred = clf.predict(X_test)

# Calculate the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Print the confusion matrix
print(cm)

# Calculate the accuracy score
accuracy = accuracy_score(y_test, y_pred)

# Print the accuracy score
print(accuracy)

# Print the mapping between encoded labels and original values
print(label_mapping)


[[  0   0   0   0   0  16   1   1   2   0]
 [  0   0   0   1   0 125   0   3   0   0]
 [  0   0   5   4   0 108   1  10   4   0]
 [  0   0   0  23   0 276   1   7   2   0]
 [  0   0   0   0   0   2   0   1   0   0]
 [  0   0   1  10   0 606   2   6   7   0]
 [  0   0   1   4   0 177   4   8   5   0]
 [  0   0   1   1   0 216   0  49   4   0]
 [  0   0   0  11   0 241   1  12  11   0]
 [  0   0   0   2   0  24   0   2   0   0]]
0.3491745872936468
{2: 'Anger', 8: 'Sarcasm', 3: 'Excitement', 1: 'Affection/Love', 5: 'Happy', 7: 'Sad', 6: 'Humour', 4: 'Fear', 0: 'Abusive', 9: 'Surprise', 10: nan}
